### PR TITLE
Campaign Cypress test suite

### LINKED ISSUE #443: Cypress Tests for Campaign Creation and Modification
## Description

Write E2E Cypress tests for #365 Campaign Creation and Modification.

## Possible Implementation

- Create a Campaign
- Edit a Campaign
- Generate a new invite code

### PR DESCRIPTION
**Pull request by willyyhuang**
Closes #443 

Added campaign cypress tests.

### CODE REVIEW

**Comment by willyyhuang** [comment]
> Hey @willyyhuang, everything here looks good. I suggested a correction for a typo. I would also like you to add a test to check that the user is able to generate a new invite code, since we're trying to test the user criteria for the story. I think you can use plain JavaScript for that.

afaik, a new invite code is only generated after an user is kicked, do you want me to mock that?

**Comment by willyyhuang** [comment]
> > Hey @willyyhuang, everything here looks good. I suggested a correction for a typo. I would also like you to add a test to check that the user is able to generate a new invite code, since we're trying to test the user criteria for the story. I think you can use plain JavaScript for that.
> 
> afaik, a new invite code is only generated after an user is kicked, do you want me to mock that?

The kick functionality should be tested in #444 , therefore this branch is good to review again.

**Comment by pascwhale** [comment]
The invite code criterion was moved to the [Campaign Enrollment](https://github.com/DnD-Montreal/session-tome/issues/251) issue, therefore testing the new invite code is not within the scope of this task.

**Review by pascwhale — APPROVED** [review]
Everything looks good, thank you,

**Pull request merged**
