### PR TITLE
Custom data table component

### LINKED ISSUE #164: Refactor table to re-usable DataTable
## Description

Currently tables in the front end are complete code mess, a lot of duplicate and not so readable codes.
We need to refactor the tables completely to follow a structure and to ensure it is re-usable.

Tests related to tables will have to be re-do later.

## Possible Implementation

Implement <DataTable />
https://github.com/gregnb/mui-datatables

## Out of scope

N/A 

## Requirements / Restrictions

N/A

### PR DESCRIPTION
**Pull request by willyyhuang**
Closes #164 

Created a re-usable custom data table component.

### CODE REVIEW

**Comment by m-triassi** [comment]
I'll let the other Devs review this rather than me, though i just want to check, did we assess if [this datatable package](https://react-data-table-component.netlify.app/?path=/docs/ui-library-material-ui-table--table) is usable / good rather than a custom implementation?

**Comment by willyyhuang** [comment]
> I'll let the other Devs review this rather than me, though i just want to check, did we assess if [this datatable package](https://react-data-table-component.netlify.app/?path=/docs/ui-library-material-ui-table--table) is usable / good rather than a custom implementation?

it is really not usable, due to the way they decompose columns and the data from backend, my custom implementation will allow us a lot more flexibility and especially it will be free from any additional packages which are really inconvenient to add
(I was trying multiple `dataTable` packages this afternoon, most of them don't even support typescript or have nearly no customizability

**Review by bcobo341 — COMMENTED** [review]
Everything looks good! Just need to make sure that all tests pass.

**Review by pascwhale — APPROVED** [review]
The table looks good on the Character's page. I can't wait for this to be used elsewhere as our official table component.

The only nice-to-have feature would be that clicking on the magnifying glass could put the search field in focus.

**Pull request merged**
